// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAksFjA14aty9-gDMynZ-ygso1a4kFZgPI',
    appId: '1:414484440260:web:e010c582a4f2f868e69591',
    messagingSenderId: '414484440260',
    projectId: 'beer-recipe',
    authDomain: 'beer-recipe.firebaseapp.com',
    storageBucket: 'beer-recipe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfBBWW1NC6pyDb28VrAez35TE6JKm4yqI',
    appId: '1:414484440260:android:7eec6fb3564713afe69591',
    messagingSenderId: '414484440260',
    projectId: 'beer-recipe',
    storageBucket: 'beer-recipe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6vQwNBSH1VVbO5ANXCA1-7jybMVxAVzY',
    appId: '1:414484440260:ios:96915859915e89e0e69591',
    messagingSenderId: '414484440260',
    projectId: 'beer-recipe',
    storageBucket: 'beer-recipe.appspot.com',
    iosClientId: '414484440260-ag1du7n2ujlnc746f9inb0be42b260hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.beerRecipe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6vQwNBSH1VVbO5ANXCA1-7jybMVxAVzY',
    appId: '1:414484440260:ios:96915859915e89e0e69591',
    messagingSenderId: '414484440260',
    projectId: 'beer-recipe',
    storageBucket: 'beer-recipe.appspot.com',
    iosClientId: '414484440260-ag1du7n2ujlnc746f9inb0be42b260hr.apps.googleusercontent.com',
    iosBundleId: 'com.example.beerRecipe',
  );
}
